baseURL = "https://blog.benjamin.xin/"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
pluralizeListTitles = "true" 

enableRobotsTXT = true
paginate = 10
summaryLength = 0
smartTOC = true
buildDrafts = false
buildFuture = false
